apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg-module-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reg-module
  template:
    metadata:
      labels:
        app: reg-module
    spec:
      containers:
      - name: reg-module
        image: reg-module:v1.0.${BUILD_NUMBER}  # Replace ${BUILD_NUMBER} with your actual build number
        ports:
        - containerPort: 8080
